[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "catala_devtools_fr"
version = "0.0.1"
dependencies = [
  "dynaconf",
  "panflute",
  "httpx"
]

[project.optional-dependencies]
dev = [
  "mypy",
  "pytest",
  "tox"
]
