[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "catala_devtools_fr"
version = "0.0.1"
dependencies = [
  "aiometer",
  "dynaconf",
  "httpx",
  "markdown-it-py[plugins]",
  "mdformat",
  "more-itertools",
  "typer",
]

[project.optional-dependencies]
dev = [
  "mypy",
  "pre-commit",
  "pytest",
  "tox",
]
